version: '3'
services:
  mongo:
    ports:
      - 27017:27017
    image: mongo
    restart: always
  app:
     image: momasha/mern:v1
     ports: 
       - 3000:3000
     restart: always
     links:
       - mongo
